project:
  type: book
  output-dir: docs

book:
  title: "ğŸœï¸Project Desert RoseğŸœï¸"
  author: "MASH Potatoes, (UCL CASA), 2024"
  date: "22/04/2024"
  chapters:
    - index.qmd
  favicon: "images/circl-logo.png"

format:
  html:
    theme:
      light: [journal]
      dark: [journal,darkly]
    code-copy: true
    code-link: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
    css: styles.css
    navbar: false
    sidebar: false